name: Build & Push both services to ACR (monorepo)

on:
  push:
    branches: [ "main" ]
    paths:
      - "users-api/**"
      - "products-api/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - service: users-api
            context: users-api
            image: users-api
          - service: products-api
            context: products-api
            image: products-api

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔐 Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🔑 Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 🏷️ Set version tag (short sha)
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: 🏗️ Build & Push ${{ matrix.service }}
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ matrix.image }}:latest ${{ matrix.context }}
          docker tag  ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ matrix.image }}:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ matrix.image }}:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ matrix.image }}:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ matrix.image }}:${{ steps.vars.outputs.TAG }}